name: Semgrep Code Analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        id: semgrep_scan
        continue-on-error: true
        run: |
          semgrep --config ./semgrep.yml --json > semgrep_results.json

      - name: Display Semgrep Results
        if: failure() # This step runs only if Semgrep found issues
        run: |
          echo "Semgrep found vulnerabilities:"
          semgrep --config ./semgrep.yml --json | jq .

  
      - name: Create GitHub Issues for Semgrep Findings
        if: steps.semgrep_scan.outcome == 'failure'
        run: |
          python create_issues.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
